name: Mentions workflow
on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-mentions:
    name: Update this repo's README with mentions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: node mentions.js
